# Autogenerated wrapper script for GCCToolchain_jll for armv7l-linux-gnueabihf
JLLWrappers.@generate_wrapper_header("GCCToolchain")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
