# Autogenerated wrapper script for GCCToolchain_jll for i686-linux-gnu
JLLWrappers.@generate_wrapper_header("GCCToolchain")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
